### ISSUE TITLE
Typo of MAP equation

### ISSUE THREAD

**Issue by Yienschwen** [wiseodd/wiseodd.github.io#5]
Hi there, your [post on MLE vs MAP](https://wiseodd.github.io/techblog/2017/01/01/mle-vs-map/)  helped me a lot in understanding MAP, but I think I found a typo in your MAP equation, that:
The probability of parameter *should be factored out* after taken logarithm.

See also [Wikipedia example here](https://en.wikipedia.org/wiki/Maximum_a_posteriori_estimation#Example)

**Comment by wiseodd** [comment]
Hi Yienschwen,

Thanks for the remark.
I think it is already very obvious that $\log ab = \log a + \log b$, so I didn't explicitly write that. Furthermore the current form is already sufficient for the discussion presented in the post.

Cheers,
Agustinus

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Yienschwen** [comment]
Thank you for your kindly reply.
