### ISSUE TITLE
Reusing wiseodd.github.io template

### ISSUE THREAD

**Issue by euler16** [wiseodd/wiseodd.github.io#6]
Hi,
I want to reuse your template for my own site. could you provide me the  source from where you modified/obtained this template.

**Comment by euler16** [comment]
Basically I want to know the set of commands or tools you use to build your site locally. I tried Jekyll build but it doesn't work with your repository.
When I did Jekyll serve directly without doing jekyll build, the web page got messed up.

**Comment by wiseodd** [comment]
Hi, it's basically just pure vanilla Jekyll, plus some plugins (which you can just install easily via gem, e.g. `gem install jekyll-pagination`. Just try do `jekyll serve` and if any plugin is missing it will let you know and you can just install it.
