### ISSUE TITLE
Errata in MLE vs MAP blog post

### ISSUE THREAD

**Issue by cocoaaa** [wiseodd/wiseodd.github.io#7]
Hi, while reading through your MLE vs MAP blog [post](https://wiseodd.github.io/techblog/2017/01/01/mle-vs-map/), I noticed an errata: the theta_map should be an argmax of {logP(theta) + sum(log likelihoods)} not the product of the two terms (because of the log operation):
![image](https://user-images.githubusercontent.com/8037983/60627635-80582080-9da3-11e9-9171-c6485f6d3347.png)

It doesn't affect what follows, but would be nice if updated correctly. 
Thanks for great articles!

**Comment by wiseodd** [comment]
Thanks a lot for the errata. It's now fixed.
